In [5]:
#GET BASE KNOWLEDGE 

import pandas as pd

# تحميل مجموعة البيانات الجديدة
medical_dataset = pd.read_csv('heart.csv')

# عرض مجموعة البيانات
#print(medical_dataset.head())
medical_dataset

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [6]:
# عرض القيم الفريدة في عمود الهدف
print(set(medical_dataset['target']))

{0, 1}

In [7]:
#SPLIT DB  

from sklearn.model_selection import train_test_split

# استخدام الدالة لتقسيم البيانات، الحصول على 3% للاختبار و 97% للتدريب
train_data, test_data = train_test_split(medical_dataset, test_size=0.03, random_state=42)

# طباعة الأشكال (الصفوف × الأعمدة) لمجموعتي البيانات
print("Train data shape:", train_data.shape)
print("Test data shape:", test_data.shape)

Train data shape: (994, 14)
Test data shape: (31, 14)

In [8]:



#CREATE MODEL

from sklearn.tree import DecisionTreeClassifier

# إنشاء نموذج Decision Tree Classifier
model = DecisionTreeClassifier(random_state=1)

# الحصول على عمود الهدف، ليستخدم كهدف للتصنيف
train_diagnoses = train_data['target']

# إسقاط عمود الهدف للحصول على الأعراض
train_patient_symptoms = train_data.drop(columns=['target'])

# بناء شجرة القرار
model.fit(train_patient_symptoms, train_diagnoses)

DecisionTreeClassifier(random_state=1)

In [9]:

# TEST DATA

from sklearn.metrics import accuracy_score, confusion_matrix

# إسقاط عمود الهدف للحصول على الأعراض للاختبار
test_patient_symptoms = test_data.drop(columns=['target'])

# الحصول على عمود الهدف للاختبار
test_diagnoses = test_data['target']

# التخمين
pred = model.predict(test_patient_symptoms)

# طباعة النتائج
print("Predictions:", pred)

# طباعة دقة النموذج
print("Accuracy Score:", accuracy_score(test_diagnoses, pred))

Predictions: [1 1 0 1 0 1 0 0 1 0 1 0 1 1 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 0 0]
Accuracy Score: 1.0

In [10]:

# طباعة مصفوفة الارتباك
print("Confusion Matrix:\n", confusion_matrix(test_diagnoses, pred))

Confusion Matrix:
 [[16  0]
 [ 0 15]]